# Lecture 1107

In [1]:
import pandas as pd
import altair as alt

In [2]:
berkeley_311 = pd.read_csv('berkeley_311_clean.csv', 
    dtype={
        'Case_ID': object,
    },
    parse_dates=['Date_Opened', 'Date_Closed', 'Close_Time']
)

In [3]:
berkeley_311

,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location,Close_Time
0,121000877593,2021-09-16 06:23:23,Closed,2021-09-20 11:22:22,"Facilities, Electrical & Property Management",Parks/Marina Building Services,Keys / Locks,Property,NaN,"Intersection of Browning and Addison, BERKELEY...",Berkeley,CA,Berkeley,NaN,NaN,NaN,4 days 04:58:59
1,121000876647,2021-09-13 10:50:00,Open,NaT,Refuse and Recycling,Residential,Residential Bulky Pickup,Property,054 180702800,1722 DWIGHT WAY,Berkeley,CA,Berkeley,37.862656,-122.275461,"(37.86265624, -122.27546088)",NaN
2,121000809740,2020-11-06 16:51:00,Closed,2020-11-09 01:52:57,General Questions/information,Miscellaneous,Miscellaneous Service Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,2 days 09:01:57
3,121000809739,2020-11-06 16:38:00,Closed,2020-11-09 01:41:12,General Questions/information,Miscellaneous,Miscellaneous Service Request,Property,060 249305600,1411 GRIZZLY PEAK BLVD,Berkeley,CA,Berkeley,37.884799,-122.247874,"(37.88479918, -122.24787412)",2 days 09:03:12
4,121000793663,2020-09-01 11:32:00,Closed,2020-09-01 11:36:00,Other Account Services and Billing,Marina,Payment Collection - Marina,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,0 days 00:04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
648190,121000963461,2022-10-22 12:00:20,Open,NaT,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Property,059 226603200,1413 BONITA AVE,Berkeley,CA,Berkeley,37.881127,-122.272577,"(37.8811269, -122.2725769)",NaN
648191,121000963479,2022-10-22 22:52:40,Open,NaT,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,NaN
648192,121000963164,2022-10-20 19:50:00,Closed,2022-10-22 07:12:00,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Property,054 173001100,1617 STUART ST,Berkeley,CA,Berkeley,37.857543,-122.276810,"(37.85754346, -122.27680958)",1 days 11:22:00
648193,121000963464,2022-10-22 13:51:47,Open,NaT,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,NaN
648194,121000963336,2022-10-21 13:25:00,Closed,2022-10-22 07:40:09,"Streets, Utilities, and Transportation",Clean City Program,Illegal Dumping - City Property,Property,052 155202300,1908 WOOLSEY ST,Berkeley,CA,Berkeley,37.851653,-122.269543,"(37.85165348, -122.26954337)",0 days 18:15:09

## Some tips

### `df.reset_index()` vs `df.reset_index(drop=True)`

In [6]:
# sort the data
berkeley_311 = berkeley_311.sort_values(by=['Date_Opened']).copy()
berkeley_311.head()

,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location,Close_Time
520464,121000000003,2010-02-05 11:46:34,Closed,2010-02-05 11:46:54,Refuse and Recycling,Request,Residential - Service Start,Unknown,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,0 days 00:00:20
531026,121000000005,2010-02-17 11:44:43,Closed,2013-09-26 14:42:15,"Facilities, Electrical & Property Management",Electrical Services,Street Lights - Repair,Street,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,1317 days 02:57:32
399398,121000000006,2010-02-17 13:38:24,Closed,2013-09-26 14:42:00,"Facilities, Electrical & Property Management",Electrical Services,Street Lights - Repair,Street,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,1317 days 01:03:36
554448,121000000007,2010-02-24 10:18:24,Closed,2013-09-26 14:41:41,"Facilities, Electrical & Property Management",Electrical Services,Street Lights - Repair,Street,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,1310 days 04:23:17
327993,121000000012,2010-03-11 07:05:52,Closed,2013-09-26 14:41:23,"Facilities, Electrical & Property Management",Electrical Services,Street Lights - Repair,Street,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,1295 days 07:35:31

In [7]:
berkeley_311.reset_index() # this adds a new column called `index` that was the old index.

,index,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location,Close_Time
0,520464,121000000003,2010-02-05 11:46:34,Closed,2010-02-05 11:46:54,Refuse and Recycling,Request,Residential - Service Start,Unknown,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,0 days 00:00:20
1,531026,121000000005,2010-02-17 11:44:43,Closed,2013-09-26 14:42:15,"Facilities, Electrical & Property Management",Electrical Services,Street Lights - Repair,Street,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,1317 days 02:57:32
2,399398,121000000006,2010-02-17 13:38:24,Closed,2013-09-26 14:42:00,"Facilities, Electrical & Property Management",Electrical Services,Street Lights - Repair,Street,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,1317 days 01:03:36
3,554448,121000000007,2010-02-24 10:18:24,Closed,2013-09-26 14:41:41,"Facilities, Electrical & Property Management",Electrical Services,Street Lights - Repair,Street,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,1310 days 04:23:17
4,327993,121000000012,2010-03-11 07:05:52,Closed,2013-09-26 14:41:23,"Facilities, Electrical & Property Management",Electrical Services,Street Lights - Repair,Street,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,1295 days 07:35:31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
648190,648185,121000963476,2022-10-22 16:50:29,Open,NaT,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Property,059 227301301,1430 JOSEPHINE ST,Berkeley,CA,Berkeley,37.880056,-122.275429,"(37.88005617, -122.27542872)",NaN
648191,648167,121000963477,2022-10-22 17:07:57,Open,NaT,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Unknown,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,NaN
648192,648188,121000963478,2022-10-22 17:08:54,Open,NaT,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Unknown,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,NaN
648193,648191,121000963479,2022-10-22 22:52:40,Open,NaT,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,NaN
648194,648147,121000963480,2022-10-23 02:59:05,Open,NaT,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,NaN

In [9]:
berkeley_311.reset_index(drop=True) # this resets the actual index

,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location,Close_Time
0,121000000003,2010-02-05 11:46:34,Closed,2010-02-05 11:46:54,Refuse and Recycling,Request,Residential - Service Start,Unknown,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,0 days 00:00:20
1,121000000005,2010-02-17 11:44:43,Closed,2013-09-26 14:42:15,"Facilities, Electrical & Property Management",Electrical Services,Street Lights - Repair,Street,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,1317 days 02:57:32
2,121000000006,2010-02-17 13:38:24,Closed,2013-09-26 14:42:00,"Facilities, Electrical & Property Management",Electrical Services,Street Lights - Repair,Street,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,1317 days 01:03:36
3,121000000007,2010-02-24 10:18:24,Closed,2013-09-26 14:41:41,"Facilities, Electrical & Property Management",Electrical Services,Street Lights - Repair,Street,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,1310 days 04:23:17
4,121000000012,2010-03-11 07:05:52,Closed,2013-09-26 14:41:23,"Facilities, Electrical & Property Management",Electrical Services,Street Lights - Repair,Street,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,1295 days 07:35:31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
648190,121000963476,2022-10-22 16:50:29,Open,NaT,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Property,059 227301301,1430 JOSEPHINE ST,Berkeley,CA,Berkeley,37.880056,-122.275429,"(37.88005617, -122.27542872)",NaN
648191,121000963477,2022-10-22 17:07:57,Open,NaT,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Unknown,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,NaN
648192,121000963478,2022-10-22 17:08:54,Open,NaT,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Unknown,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,NaN
648193,121000963479,2022-10-22 22:52:40,Open,NaT,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,NaN
648194,121000963480,2022-10-23 02:59:05,Open,NaT,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,NaN

### Naming your new columns

Do this in a separate cleaning notebook.
- First, consider cleaning up the column names.
- Use an underscore ahead of a new column name to indicate it's a column you created.

In [11]:
berkeley_311.columns

Index(['Case_ID', 'Date_Opened', 'Case_Status', 'Date_Closed',
       'Request_Category', 'Request_SubCategory', 'Request_Detail',
       'Object_Type', 'APN', 'Street_Address', 'City', 'State', 'Neighborhood',
       'Latitude', 'Longitude', 'Location', 'Close_Time'],
      dtype='object')

Remember list comprehensions!?

In [14]:
# lowercase all columns
berkeley_311.columns = [cols.lower() for cols in berkeley_311.columns]
berkeley_311.columns

Index(['case_id', 'date_opened', 'case_status', 'date_closed',
       'request_category', 'request_subcategory', 'request_detail',
       'object_type', 'apn', 'street_address', 'city', 'state', 'neighborhood',
       'latitude', 'longitude', 'location', 'close_time'],
      dtype='object')

In [16]:
# add an underscore ahead of the column you calculated
berkeley_311.rename(columns={'close_time': '_close_time'}, inplace=True)

In [17]:
berkeley_311.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 648195 entries, 520464 to 648147
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   case_id              648195 non-null  object
 1   date_opened          648195 non-null  datetime64[ns]
 2   case_status          648195 non-null  object
 3   date_closed          615523 non-null  datetime64[ns]
 4   request_category     648195 non-null  object
 5   request_subcategory  648195 non-null  object
 6   request_detail       648195 non-null  object
 7   object_type          648195 non-null  object
 8   apn                  371225 non-null  object
 9   street_address       408719 non-null  object
 10  city                 648195 non-null  object
 11  state                648195 non-null  object
 12  neighborhood         648195 non-null  object
 13  latitude             366482 non-null  float64
 14  longitude            366482 non-null  float64
 15  location             366482 non-null  object
 16  _close_time          615523 non-null  object
dtypes: datetime64[ns](2), float64(2), object(13)
memory usage: 89.0+ MB

### `groupbys`

You don't have to run this line without .count():

```python
oakland_311.groupby([pd.Grouper(key='DATETIMEINIT', axis=0, freq='A')])
```

### Using `df.value_count()` and `df.to_frame()`

Kind of like `df.groupby([cols]).count()` but faster and cleaner.

You can convert a Series to a Dataframe using `series.to_frame()`.

In [29]:
berkeley_311[['request_category', 'request_subcategory']].value_counts().to_frame().reset_index()

                 request_category           request_subcategory       0
0            Refuse and Recycling                   Residential  114212
1   General Questions/information                 Miscellaneous  108350
2            Refuse and Recycling                    Commercial   92985
3            Refuse and Recycling  Account Services and Billing   52930
4   General Questions/information                  Front Office   44991
..                            ...                           ...     ...
60               Business License                     Solicitor       2
61  General Questions/information                   Back Office       2
62               Business License           Motor Vehicle Sales       1
63               Business License                  Food Vendors       1
64               Outside Agencies                          AT&T       1

[65 rows x 3 columns]

In [27]:
# compare with
berkeley_311.groupby(['request_category', 'request_subcategory']).count()[['case_id']].reset_index().sort_values(by=['case_id'], ascending=False)

                 request_category           request_subcategory  case_id
53           Refuse and Recycling                   Residential   114212
32  General Questions/information                 Miscellaneous   108350
51           Refuse and Recycling                    Commercial    92985
50           Refuse and Recycling  Account Services and Billing    52930
31  General Questions/information                  Front Office    44991
..                            ...                           ...      ...
17               Business License                     Solicitor        2
30  General Questions/information                   Back Office        2
11               Business License           Motor Vehicle Sales        1
6                Business License                  Food Vendors        1
45               Outside Agencies                          AT&T        1

[65 rows x 3 columns]

### Scatterplot altair using annual_summary

In [30]:
summary = pd.read_csv('berkeley_311_annual_summary.csv')
summary

   Year  Case_Count  Close_Time_Days
0  2011       39708        86.215602
1  2012       46643        16.003565
2  2013       50309         7.965579
3  2014       53531        10.768397
4  2015       50334         4.334236
5  2016       50573         3.912419
6  2017       51325         3.639792
7  2018       57636         3.175874
8  2019       58633         3.705052
9  2020       56145         2.195741

In [34]:
alt.Chart(summary).mark_circle(size=60).encode(
    x=alt.X('Case_Count', axis=alt.Axis(title='Annual case count')),
    y=alt.Y('Close_Time_Days', axis=alt.Axis(title='Median days to close case')),
    tooltip=['Year']
).properties(
    title={
        'text': 'Berkeley 311 calls',
        'subtitle' : ['Case counts x Close Time (in days)']
    },
    height=200,
    width=400
).interactive()

alt.Chart(...)