# Lecture 1017

Introduction to pandas using Berkeley 311 call data.

## Modules

A **module** is a way for Python to store functions and variables so they can be reused. You `import` modules to use those functions and variables. Typically, all the `import` statements are the top of a file or notebook.

In [1]:
import pandas as pd
import requests

The `requests` module is already built into Python. DataHub already has `pandas` installed; if you're working on your own computer, you will need to install `pandas` yourself.

A **package** is a kind of module that uses "dotted module names." That just means you can use methods with the name of the package followed by a period and the method, e.g. `requests.get()`.

When you `import` a module, you can give it an alias using `as`. Above, we gave the pandas module the alias of `pd`. That means we can call the library’s methods using `pd.read_csv()` instead of `pandas.read_csv()`. We always `import pandas as pd` because that's what the pandas-using community has decided as a convention.

Sometimes we call modules like pandas "libraries." That's a general software term; there's no special Python thing called "library."

## What is pandas?

It's a Python Data Analysis library.

[Pandas](https://pandas.pydata.org/) is a library that allows you to view table data and perform lots of different kinds of operations on that table. In pandas, a table is called a **dataframe**. If you’ve used Excel or Google Sheets, a dataframe should look familiar to you. There are rows and columns. You have column headers. You have discrete rows.

## Download data

We're going to download [311 call data](https://data.cityofberkeley.info/311/311-Cases-COB/bscu-qpbu) from the City of Berkeley's Open Data Portal. You can run the cell below. It will download the data into a file called `berkeley_311.csv`.

If you want to download something straight from the Internet again, you can copy this code but swap out the url and the file name. (But don't forget to `import requests` at the top of your notebook.)

In [2]:
url = 'https://data.cityofberkeley.info/api/views/bscu-qpbu/rows.csv?accessType=DOWNLOAD'
r = requests.get(url, allow_redirects=False)

# write the content of the request into a file called `berkeley_311.csv`
open('berkeley_311.csv', 'wb').write(r.content)

129037547

## Import the csv into a `pandas` dataframe

We use a method called `pd.read_csv()` to import a csv file into a dataframe.

Make sure you assign the dataframe into a variable. Below, we're calling the dataframe `berkeley_311_original`.

In [3]:
berkeley_311_original = pd.read_csv('berkeley_311.csv')

In these notes, I'm going to use the term `df` to stand for 'dataframe' — you will see `df` when you're searching the Internet for answers. In your actual work, you'll replace `df` with whatever you called your dataframe; in this case, that's `berkeley_311_original`.

## View data

### `df.head()` and `df.tail()`

Use `df.head()` to view the first 5 rows and the last 5 rows of the dataframe.

In [4]:
berkeley_311_original.head()

,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location
0,121000809740,11/06/2020 04:51:00 PM,Closed,11/09/2020 01:52:57 AM,General Questions/information,Miscellaneous,Miscellaneous Service Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
1,121000809739,11/06/2020 04:38:00 PM,Closed,11/09/2020 01:41:12 AM,General Questions/information,Miscellaneous,Miscellaneous Service Request,Property,060 249305600,1411 GRIZZLY PEAK BLVD,Berkeley,CA,Berkeley,37.884799,-122.247874,"(37.88479918, -122.24787412)"
2,121000793663,09/01/2020 11:32:00 AM,Closed,09/01/2020 11:36:00 AM,Other Account Services and Billing,Marina,Payment Collection - Marina,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
3,121000797043,09/15/2020 01:07:00 PM,Closed,11/09/2020 12:15:48 PM,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
4,121000750353,02/11/2020 11:40:00 AM,Closed,02/21/2020 01:17:00 PM,Public Records Act,Request,zMulti-Department,Organisation,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN

You'll notice that there are numbers `0`, `1`, `2`, `3`, and `4` added to the dataframe to the left. That's called the **index** of the dataframe. An index is basically a row id.

You can also use `df.head(20)` to view the first 20 rows.

How would you view the last 5 rows? Use `df.tail()`. (`head` and `tail` are commonly used methods to read files.)

In [5]:
berkeley_311_original.tail()

,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location
588079,121000870206,08/16/2021 06:43:00 PM,Closed,08/24/2021 08:54:17 AM,Refuse and Recycling,Commercial,Commercial Customer Complaint,Property,NaN,"Intersection of Shattuck and Cedar, BERKELEY, CA",Berkeley,CA,Berkeley,NaN,NaN,NaN
588080,121000871866,08/24/2021 08:33:00 AM,Open,NaN,Refuse and Recycling,Residential,Residential Missed Pickup,Property,063 295600301,30 ACACIA AVE,Berkeley,CA,Berkeley,37.900258,-122.268583,"(37.90025808, -122.26858321)"
588081,121000871870,08/24/2021 08:38:11 AM,Closed,08/24/2021 04:36:08 PM,Refuse and Recycling,Account Services and Billing,Payment Collection - Refuse and Recycling,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
588082,121000872015,08/24/2021 12:12:38 PM,Closed,08/24/2021 04:36:30 PM,Refuse and Recycling,Account Services and Billing,Payment Collection - Refuse and Recycling,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
588083,121000871566,08/23/2021 10:05:00 AM,Closed,08/24/2021 02:58:00 PM,"Streets, Utilities, and Transportation",Clean City Program,Illegal Dumping - City Property,Property,NaN,"Intersection of Euclid and Virginia, BERKELEY, CA",Berkeley,CA,Berkeley,NaN,NaN,NaN

If you call the dataframe on its own, you'll get both the first 5 rows and the last 5 rows.

In [6]:
berkeley_311_original

,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location
0,121000809740,11/06/2020 04:51:00 PM,Closed,11/09/2020 01:52:57 AM,General Questions/information,Miscellaneous,Miscellaneous Service Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
1,121000809739,11/06/2020 04:38:00 PM,Closed,11/09/2020 01:41:12 AM,General Questions/information,Miscellaneous,Miscellaneous Service Request,Property,060 249305600,1411 GRIZZLY PEAK BLVD,Berkeley,CA,Berkeley,37.884799,-122.247874,"(37.88479918, -122.24787412)"
2,121000793663,09/01/2020 11:32:00 AM,Closed,09/01/2020 11:36:00 AM,Other Account Services and Billing,Marina,Payment Collection - Marina,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
3,121000797043,09/15/2020 01:07:00 PM,Closed,11/09/2020 12:15:48 PM,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
4,121000750353,02/11/2020 11:40:00 AM,Closed,02/21/2020 01:17:00 PM,Public Records Act,Request,zMulti-Department,Organisation,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588079,121000870206,08/16/2021 06:43:00 PM,Closed,08/24/2021 08:54:17 AM,Refuse and Recycling,Commercial,Commercial Customer Complaint,Property,NaN,"Intersection of Shattuck and Cedar, BERKELEY, CA",Berkeley,CA,Berkeley,NaN,NaN,NaN
588080,121000871866,08/24/2021 08:33:00 AM,Open,NaN,Refuse and Recycling,Residential,Residential Missed Pickup,Property,063 295600301,30 ACACIA AVE,Berkeley,CA,Berkeley,37.900258,-122.268583,"(37.90025808, -122.26858321)"
588081,121000871870,08/24/2021 08:38:11 AM,Closed,08/24/2021 04:36:08 PM,Refuse and Recycling,Account Services and Billing,Payment Collection - Refuse and Recycling,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
588082,121000872015,08/24/2021 12:12:38 PM,Closed,08/24/2021 04:36:30 PM,Refuse and Recycling,Account Services and Billing,Payment Collection - Refuse and Recycling,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
588083,121000871566,08/23/2021 10:05:00 AM,Closed,08/24/2021 02:58:00 PM,"Streets, Utilities, and Transportation",Clean City Program,Illegal Dumping - City Property,Property,NaN,"Intersection of Euclid and Virginia, BERKELEY, CA",Berkeley,CA,Berkeley,NaN,NaN,NaN

### `df.info()`

Use `df.info()` to get more information on the dataframe. In particular, this method is useful in that it shows us the column names and what `dtype` the column is. (I'll explain `dtype` below.)

In [7]:
berkeley_311_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 588084 entries, 0 to 588083
Data columns (total 16 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Case_ID              588084 non-null  int64
 1   Date_Opened          588084 non-null  object
 2   Case_Status          588084 non-null  object
 3   Date_Closed          561754 non-null  object
 4   Request_Category     588084 non-null  object
 5   Request_SubCategory  588084 non-null  object
 6   Request_Detail       588084 non-null  object
 7   Object_Type          588084 non-null  object
 8   APN                  331564 non-null  object
 9   Street_Address       365475 non-null  object
 10  City                 588084 non-null  object
 11  State                588084 non-null  object
 12  Neighborhood         588084 non-null  object
 13  Latitude             327333 non-null  float64
 14  Longitude            327333 non-null  float64
 15  Location             327333 non-null  object
dtypes: float64(2), int64(1), object(13)
memory usage: 71.8+ MB

### What is dtype?

You remember when we talked about Python **types**, like `int`, `float`, and `string`? Above, we have `int64` instead of `int`, and `float64` instead of `float`. (`object` is pretty close to `string`, but not exactly.)

Here, **dtype** stands for **data type** and comes from a module called `numpy`. Even though we did not `import numpy`, the pandas module imported `numpy` within its own code.

Side note on dtypes: Sometimes, data doesn't import correctly, and you have to `df.read_csv()` again while simultaneously specifying the dtype. We're not going to do that today because it looks like most of the data imported OK. But we will convert the dtype of two columns so we can perform certain calculations.

Let's take a look at a bit of the dataframe again.

In [8]:
berkeley_311_original.head()

,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location
0,121000809740,11/06/2020 04:51:00 PM,Closed,11/09/2020 01:52:57 AM,General Questions/information,Miscellaneous,Miscellaneous Service Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
1,121000809739,11/06/2020 04:38:00 PM,Closed,11/09/2020 01:41:12 AM,General Questions/information,Miscellaneous,Miscellaneous Service Request,Property,060 249305600,1411 GRIZZLY PEAK BLVD,Berkeley,CA,Berkeley,37.884799,-122.247874,"(37.88479918, -122.24787412)"
2,121000793663,09/01/2020 11:32:00 AM,Closed,09/01/2020 11:36:00 AM,Other Account Services and Billing,Marina,Payment Collection - Marina,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
3,121000797043,09/15/2020 01:07:00 PM,Closed,11/09/2020 12:15:48 PM,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
4,121000750353,02/11/2020 11:40:00 AM,Closed,02/21/2020 01:17:00 PM,Public Records Act,Request,zMulti-Department,Organisation,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN

There are 2 columns that we want to convert. **Date_Opened** and **Date_Closed** are both `object` dtype, but we want to change them to a `datetime64` dtype. That allows us to do some math operations, like sort by the earliest date in the dataframe.

In [9]:
berkeley_311_original['Date_Opened'].min()

'01/01/2014 02:44:55 PM'

In [10]:
berkeley_311_original['Date_Opened'].max()

'12/31/2020 12:57:00 PM'

The operations above are wrong — they are sorted by string, not by actual date! We saw 2021 data when we called the df.tail() method earlier.

## Properly type the data

### Copy the original dataframe

Before we start convert the 2 columns, let's copy the original dataframe into a new dataframe. Below, I'm going to use `df.copy()` to create a copy of the original dataframe. We're not going to alter the original dataframe at all. That way, if we run into any problems later, we can compare our edited dataframe with the original dataframe.

In [11]:
berkeley_311 = berkeley_311_original.copy()

### Convert columns to `datetime`

Let's convert **Date_Opened** first so we can contrast the two columns. The syntax for this conversion is:

```python
df['column_name'] = pd.to_datetime(df['column_name'])
```

Note: This might take a long time.

In [12]:
berkeley_311['Date_Opened'] = pd.to_datetime(berkeley_311['Date_Opened'])

By the way, `berkeley_311['Date_Opened']` is a pandas **series**. We don't have to worry too much about that right now, but I want you to have to the right terminology. We're converting a series to a version of itself that passed through the `pd.to_datetime()` method.

Look at the dataframe now and compare **Date_Opened** and **Date_Closed**.

In [13]:
berkeley_311.head()

,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location
0,121000809740,2020-11-06 16:51:00,Closed,11/09/2020 01:52:57 AM,General Questions/information,Miscellaneous,Miscellaneous Service Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
1,121000809739,2020-11-06 16:38:00,Closed,11/09/2020 01:41:12 AM,General Questions/information,Miscellaneous,Miscellaneous Service Request,Property,060 249305600,1411 GRIZZLY PEAK BLVD,Berkeley,CA,Berkeley,37.884799,-122.247874,"(37.88479918, -122.24787412)"
2,121000793663,2020-09-01 11:32:00,Closed,09/01/2020 11:36:00 AM,Other Account Services and Billing,Marina,Payment Collection - Marina,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
3,121000797043,2020-09-15 13:07:00,Closed,11/09/2020 12:15:48 PM,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
4,121000750353,2020-02-11 11:40:00,Closed,02/21/2020 01:17:00 PM,Public Records Act,Request,zMulti-Department,Organisation,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN

See how they look different? You can also call `df.info()` again.

In [14]:
berkeley_311.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 588084 entries, 0 to 588083
Data columns (total 16 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Case_ID              588084 non-null  int64
 1   Date_Opened          588084 non-null  datetime64[ns]
 2   Case_Status          588084 non-null  object
 3   Date_Closed          561754 non-null  object
 4   Request_Category     588084 non-null  object
 5   Request_SubCategory  588084 non-null  object
 6   Request_Detail       588084 non-null  object
 7   Object_Type          588084 non-null  object
 8   APN                  331564 non-null  object
 9   Street_Address       365475 non-null  object
 10  City                 588084 non-null  object
 11  State                588084 non-null  object
 12  Neighborhood         588084 non-null  object
 13  Latitude             327333 non-null  float64
 14  Longitude            327333 non-null  float64
 15  Location             327333 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(12)
memory usage: 71.8+ MB

Let's now convert the 2nd column `Date_Closed`:

In [15]:
berkeley_311['Date_Closed'] = pd.to_datetime(berkeley_311['Date_Closed'])

And let's take a peek at the change:

In [16]:
berkeley_311.head()

,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location
0,121000809740,2020-11-06 16:51:00,Closed,2020-11-09 01:52:57,General Questions/information,Miscellaneous,Miscellaneous Service Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
1,121000809739,2020-11-06 16:38:00,Closed,2020-11-09 01:41:12,General Questions/information,Miscellaneous,Miscellaneous Service Request,Property,060 249305600,1411 GRIZZLY PEAK BLVD,Berkeley,CA,Berkeley,37.884799,-122.247874,"(37.88479918, -122.24787412)"
2,121000793663,2020-09-01 11:32:00,Closed,2020-09-01 11:36:00,Other Account Services and Billing,Marina,Payment Collection - Marina,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
3,121000797043,2020-09-15 13:07:00,Closed,2020-11-09 12:15:48,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN
4,121000750353,2020-02-11 11:40:00,Closed,2020-02-21 13:17:00,Public Records Act,Request,zMulti-Department,Organisation,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN

By the way, you might notice that we call `df.head()` and `df.tail()` a lot to check our work. That's OK. Later on, you will be able to run more code at once before calling one of those methods, but for now, it's good to check your work often.

### .min() and .max()

Now we can find the earliest date and the latest date of both columns, by performing `series.min()` and `series.max()` on these series. (There's no equivalent of `df`/dataframe for **series**, unfortunately.)

In [17]:
berkeley_311['Date_Opened'].min()

Timestamp('2010-02-05 11:46:34')

In [18]:
berkeley_311['Date_Opened'].max()

Timestamp('2021-10-25 00:36:07')

The min and max tell us that the year 2010 is not complete (and for that matter, neither is the current year, although we wouldn't need pandas to tell us that). If we analyze the data by year later, we might want to exclude 2010 and 2021 data.

### Get the difference of the two date columns

Pandas allows you to get the difference of two dates by literally subtracting one datetime column from another. We'll create a new column called **Close_Time** that shows us how long it took for a case to be closed.

In [19]:
berkeley_311['Close_Time'] = berkeley_311['Date_Closed'] - berkeley_311['Date_Opened']

The resulting column will not be a `datetime` dtype. It will be a `timedelta` dtype. The term "delta" is often used to mean "change." Observe the last column:

In [20]:
berkeley_311.head()

,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location,Close_Time
0,121000809740,2020-11-06 16:51:00,Closed,2020-11-09 01:52:57,General Questions/information,Miscellaneous,Miscellaneous Service Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,2 days 09:01:57
1,121000809739,2020-11-06 16:38:00,Closed,2020-11-09 01:41:12,General Questions/information,Miscellaneous,Miscellaneous Service Request,Property,060 249305600,1411 GRIZZLY PEAK BLVD,Berkeley,CA,Berkeley,37.884799,-122.247874,"(37.88479918, -122.24787412)",2 days 09:03:12
2,121000793663,2020-09-01 11:32:00,Closed,2020-09-01 11:36:00,Other Account Services and Billing,Marina,Payment Collection - Marina,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,0 days 00:04:00
3,121000797043,2020-09-15 13:07:00,Closed,2020-11-09 12:15:48,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,54 days 23:08:48
4,121000750353,2020-02-11 11:40:00,Closed,2020-02-21 13:17:00,Public Records Act,Request,zMulti-Department,Organisation,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,10 days 01:37:00

## A brief detour into data analysis

Now that we've converted the columns, we can do some interesting operations on them.

### Mean

Get the mean of a column by calling `series.mean()`.

In [21]:
berkeley_311['Close_Time'].mean()

Timedelta('61 days 18:05:57.623203396')

The average time the city took to close a case was around 61 days. This is for the whole dataset, from early 2010 to now.

### Median

In [22]:
berkeley_311['Close_Time'].median()

Timedelta('5 days 08:07:38.500000')

But the median time was around 5 days.

### Min

In [23]:
berkeley_311['Close_Time'].min()

Timedelta('0 days 00:00:00')

The shortest amount of time was 0 days and 0 seconds. That might be a public comment that didn't require follow-up. We can check on that later.

### Max

In [24]:
berkeley_311['Close_Time'].max()

Timedelta('3373 days 22:56:59')

One case seems to have taken 3,373 days! That's almost 10 years. That seems like way too long. There might be an error here.

Let's take a quick detour into _subsetting_ the data. That means to take a smaller set of the data based on some conditions. I'll explain how to subset more later, but for now, check out the following code:

In [25]:
berkeley_311[berkeley_311['Close_Time'] >= '3373 days']

,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location,Close_Time
19239,121000033912,2010-12-08 12:52:11,Closed,2020-03-04 11:49:10,Refuse and Recycling,Account Services and Billing,Payment Collection - Refuse and Recycling,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,3373 days 22:56:59

It's hard to know why it took so long to close this case without asking the city for more information.

### Sort data

We can even look at the top 10 cases that took the longest time to resolve. You'll use the `df.sort_values()` method.

Let's break down the below code before we run it. You can see there are 2 options within the parentheses for `.sort_values()`:
```python
by=['Close_Time'], ascending=False
```

The `by` argument tells us which column we will sort the dataframe by. You always need to include this argument. You can sort by multiple columns, too.

The optional `ascending` argument tells us if we want the dataframe to sort from smallest to largest or earliest to latest. By default, `ascending` is set to `True`, so we're going to change it here so it's `False`.

Next, I don't want to see the entire dataframe, just the first 10 rows. So I'm going to call `df.head(10)`.

In [26]:
berkeley_311.sort_values(by=['Close_Time'], ascending=False).head(10)

,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location,Close_Time
19239,121000033912,2010-12-08 12:52:11,Closed,2020-03-04 11:49:10,Refuse and Recycling,Account Services and Billing,Payment Collection - Refuse and Recycling,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,3373 days 22:56:59
16792,121000020729,2010-08-01 09:46:00,Closed,2019-08-25 05:45:00,"Streets, Utilities, and Transportation",Sidewalk/Street Maintenance,Potholes,Street,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,3310 days 19:59:00
19841,121000073543,2011-12-02 13:46:57,Closed,2020-01-02 12:43:50,Refuse and Recycling,Residential,Residential Service Start,Property,054 179101800,2617 MABEL ST,Berkeley,CA,Berkeley,37.859285,-122.284746,"(37.85928516, -122.28474645)",2952 days 22:56:53
120453,121000022145,2010-08-13 15:52:58,Closed,2017-06-06 10:42:43,Refuse and Recycling,Residential,Residential Missed Pickup Integration,Property,060 239500900,1115 JONES ST,Berkeley,CA,Berkeley,37.876672,-122.293798,"(37.87667247, -122.29379775)",2488 days 18:49:45
41611,121000135824,2013-04-01 13:40:04,Closed,2019-12-10 08:23:09,Traffic and Transportation,Parking,Parking Citation Dispute,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,2443 days 18:43:05
549509,121000203204,2014-07-14 13:34:26,Closed,2021-01-26 09:02:00,General Questions/information,Miscellaneous,Miscellaneous Service Request,Property,052 156312700,3125 LEWISTON AVE,Berkeley,CA,Berkeley,37.853008,-122.251309,"(37.85300822, -122.25130902)",2387 days 19:27:34
43272,121000153801,2013-08-06 09:07:33,Closed,2020-01-28 10:30:51,Refuse and Recycling,Residential,Residential Missed Pickup Integration,Property,064 429502200,26 BROOKSIDE AVE,Berkeley,CA,Berkeley,37.852015,-122.248881,"(37.85201515, -122.24888072)",2366 days 01:23:18
57271,121000171776,2013-12-09 20:01:00,Closed,2020-05-26 11:19:00,"Streets, Utilities, and Transportation",Sidewalk/Street Maintenance,Sidewalk Problem,Property,056 199503100,1325 ADDISON ST,Berkeley,CA,Berkeley,37.869268,-122.285284,"(37.86926755, -122.28528358)",2359 days 15:18:00
62850,121000127357,2013-01-28 09:47:12,Closed,2019-06-24 09:14:19,Other Account Services and Billing,Business License,Account Adjustment Research - Business License,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,2337 days 23:27:07
14642,121000154370,2013-08-09 16:17:28,Closed,2019-10-22 08:40:00,"Streets, Utilities, and Transportation",Sidewalk/Street Maintenance,Sidewalk Problem,Property,052 142801201,2026 WOOLSEY ST,Berkeley,CA,Berkeley,NaN,NaN,NaN,2264 days 16:22:32

So that's a preview of an interesting analysis we can do. I showed you one fun part before we moved onto the harder part, checking and vetting the data. Usually, we need to do that first. But we did convert the columns to datetime, which is part of making sure the data was valid.

## Clean data, part 2: Check and vet the data

### Unique identifier for every row?

First, I want to see if `Case_ID` has a unique ID for every row. Why? When you're doing a data analysis, every row should have its own unique ID. Hopefully, the agency that gave you the data has provided a unique ID. Sometimes, though, they don't. In those cases, you want to create a unique ID for every row.

I get a count of unique values by calling `.nunique()` on a column.

In [27]:
berkeley_311['Case_ID'].nunique()

588078

How many rows do we have again? We can use `df.info()` to get the number of rows, or we can scroll up to see again. I'm feeling lazy, so let's just call `len(df)`. (Do you remember that we learned `len()` for both strings and data structures earlier?)

In [28]:
len(berkeley_311)

588084

So there are 588,022 unique case IDs, but 588,028 rows in this dataframe. There might be duplicates or there could be missing data. Let's check for both.

We're going to check by **subsetting** the data.

### Subsetting

This is the general structure of how you subset data in pandas.

```python
df[ expression ]
```

That's not very descriptive. What's the _expression_? There are lots of different ways we write these expressions in pandas. I'm going to show you a handful of different kinds today, but know there are a bunch more!

Ultimately, what I want is a list of the duplicate `Case_ID`s. I'll then subset the dataframe to show any row that has a Case_ID that is on that list.


We'll first check to see which rows in `berkeley_311` are exact duplicates.

In [29]:
berkeley_311[berkeley_311.duplicated()]

Empty DataFrame
Columns: [Case_ID, Date_Opened, Case_Status, Date_Closed, Request_Category, Request_SubCategory, Request_Detail, Object_Type, APN, Street_Address, City, State, Neighborhood, Latitude, Longitude, Location, Close_Time]
Index: []

There are no exact duplicates. Now let's check specifically to see rows in which `Case_ID`s are duplicated.

In [30]:
berkeley_311[berkeley_311['Case_ID'].duplicated()]

,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location,Close_Time
59808,121000771810,2020-05-28 12:52:00,Closed,2020-05-28 14:32:46,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",0 days 01:40:46
203391,121000168293,2013-11-13 16:56:22,Closed,2013-11-18 16:16:10,Refuse and Recycling,Request,Cart Repair,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888518,-122.271781,"(37.88851766, -122.27178098)",4 days 23:19:48
229240,121000212784,2014-09-13 19:24:04,Closed,2014-09-22 08:59:39,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",8 days 13:35:35
245643,121000056432,2011-07-11 09:26:45,Closed,2011-07-14 12:56:18,Refuse and Recycling,Residential,Residential Service Start,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",3 days 03:29:33
346531,121000345232,2017-04-28 09:11:28,Closed,2017-05-04 09:32:37,Refuse and Recycling,Residential,Residential Lost or Stolen Cart,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",6 days 00:21:09
390990,121000212850,2014-09-15 09:37:45,Closed,2014-09-18 18:17:05,Refuse and Recycling,Request,Stray Cart Removal,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",3 days 08:39:20

What's annoying about this is that it only shows ONE instance of the Case_ID. What I want is a list of those Case IDs. How do I make a list of the values in one column?

First, I'm going to create a new dataframe that has the duplicated IDs. We're going to create a copy.

In [31]:
dupe_cases = berkeley_311[berkeley_311['Case_ID'].duplicated()].copy()
dupe_cases

,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location,Close_Time
59808,121000771810,2020-05-28 12:52:00,Closed,2020-05-28 14:32:46,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",0 days 01:40:46
203391,121000168293,2013-11-13 16:56:22,Closed,2013-11-18 16:16:10,Refuse and Recycling,Request,Cart Repair,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888518,-122.271781,"(37.88851766, -122.27178098)",4 days 23:19:48
229240,121000212784,2014-09-13 19:24:04,Closed,2014-09-22 08:59:39,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",8 days 13:35:35
245643,121000056432,2011-07-11 09:26:45,Closed,2011-07-14 12:56:18,Refuse and Recycling,Residential,Residential Service Start,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",3 days 03:29:33
346531,121000345232,2017-04-28 09:11:28,Closed,2017-05-04 09:32:37,Refuse and Recycling,Residential,Residential Lost or Stolen Cart,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",6 days 00:21:09
390990,121000212850,2014-09-15 09:37:45,Closed,2014-09-18 18:17:05,Refuse and Recycling,Request,Stray Cart Removal,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",3 days 08:39:20

Now we create a `list` or `array` (the numpy version of a list) of those IDs:

In [32]:
dupe_case_ids = dupe_cases['Case_ID'].to_list()

# to create an array, you can use this instead:
# dupe_case_ids = dupe_cases['Case_ID'].unique()

Now we'll call `dupe_case_ids`, so we can see what's in it.

In [33]:
dupe_case_ids

[121000771810,
 121000168293,
 121000212784,
 121000056432,
 121000345232,
 121000212850]

Now we'll subset the data by finding cases in our edited dataframe `berkeley_311`.

In [34]:
berkeley_311[berkeley_311['Case_ID'].isin(dupe_case_ids)]

,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location,Close_Time
59725,121000771810,2020-05-28 12:52:00,Closed,2020-05-28 14:32:46,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888518,-122.271781,"(37.88851766, -122.27178098)",0 days 01:40:46
59808,121000771810,2020-05-28 12:52:00,Closed,2020-05-28 14:32:46,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",0 days 01:40:46
156825,121000168293,2013-11-13 16:56:22,Closed,2013-11-18 16:16:10,Refuse and Recycling,Request,Cart Repair,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",4 days 23:19:48
168154,121000056432,2011-07-11 09:26:45,Closed,2011-07-14 12:56:18,Refuse and Recycling,Residential,Residential Service Start,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888518,-122.271781,"(37.88851766, -122.27178098)",3 days 03:29:33
175144,121000212784,2014-09-13 19:24:04,Closed,2014-09-22 08:59:39,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888518,-122.271781,"(37.88851766, -122.27178098)",8 days 13:35:35
203391,121000168293,2013-11-13 16:56:22,Closed,2013-11-18 16:16:10,Refuse and Recycling,Request,Cart Repair,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888518,-122.271781,"(37.88851766, -122.27178098)",4 days 23:19:48
217706,121000212850,2014-09-15 09:37:45,Closed,2014-09-18 18:17:05,Refuse and Recycling,Request,Stray Cart Removal,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888518,-122.271781,"(37.88851766, -122.27178098)",3 days 08:39:20
229240,121000212784,2014-09-13 19:24:04,Closed,2014-09-22 08:59:39,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",8 days 13:35:35
245643,121000056432,2011-07-11 09:26:45,Closed,2011-07-14 12:56:18,Refuse and Recycling,Residential,Residential Service Start,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",3 days 03:29:33
270504,121000345232,2017-04-28 09:11:28,Closed,2017-05-04 09:32:37,Refuse and Recycling,Residential,Residential Lost or Stolen Cart,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888518,-122.271781,"(37.88851766, -122.27178098)",6 days 00:21:09
346531,121000345232,2017-04-28 09:11:28,Closed,2017-05-04 09:32:37,Refuse and Recycling,Residential,Residential Lost or Stolen Cart,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",6 days 00:21:09
390990,121000212850,2014-09-15 09:37:45,Closed,2014-09-18 18:17:05,Refuse and Recycling,Request,Stray Cart Removal,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",3 days 08:39:20

OK, this is weird, it looks like all the cases are for the same address. Still, it's hard to tell what's going on, so I'm going to sort that dataframe by **Case_ID**.

In [35]:
berkeley_311[berkeley_311['Case_ID'].isin(dupe_case_ids)].sort_values(by=['Case_ID'])

,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location,Close_Time
168154,121000056432,2011-07-11 09:26:45,Closed,2011-07-14 12:56:18,Refuse and Recycling,Residential,Residential Service Start,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888518,-122.271781,"(37.88851766, -122.27178098)",3 days 03:29:33
245643,121000056432,2011-07-11 09:26:45,Closed,2011-07-14 12:56:18,Refuse and Recycling,Residential,Residential Service Start,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",3 days 03:29:33
156825,121000168293,2013-11-13 16:56:22,Closed,2013-11-18 16:16:10,Refuse and Recycling,Request,Cart Repair,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",4 days 23:19:48
203391,121000168293,2013-11-13 16:56:22,Closed,2013-11-18 16:16:10,Refuse and Recycling,Request,Cart Repair,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888518,-122.271781,"(37.88851766, -122.27178098)",4 days 23:19:48
175144,121000212784,2014-09-13 19:24:04,Closed,2014-09-22 08:59:39,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888518,-122.271781,"(37.88851766, -122.27178098)",8 days 13:35:35
229240,121000212784,2014-09-13 19:24:04,Closed,2014-09-22 08:59:39,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",8 days 13:35:35
217706,121000212850,2014-09-15 09:37:45,Closed,2014-09-18 18:17:05,Refuse and Recycling,Request,Stray Cart Removal,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888518,-122.271781,"(37.88851766, -122.27178098)",3 days 08:39:20
390990,121000212850,2014-09-15 09:37:45,Closed,2014-09-18 18:17:05,Refuse and Recycling,Request,Stray Cart Removal,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",3 days 08:39:20
270504,121000345232,2017-04-28 09:11:28,Closed,2017-05-04 09:32:37,Refuse and Recycling,Residential,Residential Lost or Stolen Cart,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888518,-122.271781,"(37.88851766, -122.27178098)",6 days 00:21:09
346531,121000345232,2017-04-28 09:11:28,Closed,2017-05-04 09:32:37,Refuse and Recycling,Residential,Residential Lost or Stolen Cart,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",6 days 00:21:09
59725,121000771810,2020-05-28 12:52:00,Closed,2020-05-28 14:32:46,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888518,-122.271781,"(37.88851766, -122.27178098)",0 days 01:40:46
59808,121000771810,2020-05-28 12:52:00,Closed,2020-05-28 14:32:46,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Property,061 256400200,20 TERRACE WALK,Berkeley,CA,Berkeley,37.888615,-122.272210,"(37.88861517, -122.27221016)",0 days 01:40:46

The thing that looks different is the geocoding between those cases. 

FYI, all the code we used above didn't change the original dataframe. We were subsetting, but we did not subset with a new variable. 

Now, we're going to drop the duplicated cases, and reset the variable `berkeley_311`.

In [36]:
berkeley_311 = berkeley_311.drop_duplicates(subset=['Case_ID'])

In [37]:
berkeley_311

,Case_ID,Date_Opened,Case_Status,Date_Closed,Request_Category,Request_SubCategory,Request_Detail,Object_Type,APN,Street_Address,City,State,Neighborhood,Latitude,Longitude,Location,Close_Time
0,121000809740,2020-11-06 16:51:00,Closed,2020-11-09 01:52:57,General Questions/information,Miscellaneous,Miscellaneous Service Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,2 days 09:01:57
1,121000809739,2020-11-06 16:38:00,Closed,2020-11-09 01:41:12,General Questions/information,Miscellaneous,Miscellaneous Service Request,Property,060 249305600,1411 GRIZZLY PEAK BLVD,Berkeley,CA,Berkeley,37.884799,-122.247874,"(37.88479918, -122.24787412)",2 days 09:03:12
2,121000793663,2020-09-01 11:32:00,Closed,2020-09-01 11:36:00,Other Account Services and Billing,Marina,Payment Collection - Marina,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,0 days 00:04:00
3,121000797043,2020-09-15 13:07:00,Closed,2020-11-09 12:15:48,General Questions/information,Miscellaneous,Miscellaneous Internet Request,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,54 days 23:08:48
4,121000750353,2020-02-11 11:40:00,Closed,2020-02-21 13:17:00,Public Records Act,Request,zMulti-Department,Organisation,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,10 days 01:37:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588079,121000870206,2021-08-16 18:43:00,Closed,2021-08-24 08:54:17,Refuse and Recycling,Commercial,Commercial Customer Complaint,Property,NaN,"Intersection of Shattuck and Cedar, BERKELEY, CA",Berkeley,CA,Berkeley,NaN,NaN,NaN,7 days 14:11:17
588080,121000871866,2021-08-24 08:33:00,Open,NaT,Refuse and Recycling,Residential,Residential Missed Pickup,Property,063 295600301,30 ACACIA AVE,Berkeley,CA,Berkeley,37.900258,-122.268583,"(37.90025808, -122.26858321)",NaT
588081,121000871870,2021-08-24 08:38:11,Closed,2021-08-24 16:36:08,Refuse and Recycling,Account Services and Billing,Payment Collection - Refuse and Recycling,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,0 days 07:57:57
588082,121000872015,2021-08-24 12:12:38,Closed,2021-08-24 16:36:30,Refuse and Recycling,Account Services and Billing,Payment Collection - Refuse and Recycling,Individual,NaN,NaN,Berkeley,CA,Berkeley,NaN,NaN,NaN,0 days 04:23:52
588083,121000871566,2021-08-23 10:05:00,Closed,2021-08-24 14:58:00,"Streets, Utilities, and Transportation",Clean City Program,Illegal Dumping - City Property,Property,NaN,"Intersection of Euclid and Virginia, BERKELEY, CA",Berkeley,CA,Berkeley,NaN,NaN,NaN,1 days 04:53:00

By the way, you might have noticed there's something called `NaT` in one of the rows above. `NaT` stands for _not a time_ and is kind of like `None` or an empty cell in Google Sheets. For non-time related blank cells, you'll see `NaN` (not a number) instead of `NaT`.

The difference between `None` and `NaN`/`NaT` is that the latter allows you to perform calcuations and skip any blank cells. That means, you probably need to check for how many `NaN`/`NaT` cells exist in your dataframe. If there are a lot of them, your analysis might not be valid. You can quickly check for that with the `df.info()` method we learned earlier. There's a column called `Non-Null Count`.

In [38]:
berkeley_311.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 588078 entries, 0 to 588083
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Case_ID              588078 non-null  int64
 1   Date_Opened          588078 non-null  datetime64[ns]
 2   Case_Status          588078 non-null  object
 3   Date_Closed          561748 non-null  datetime64[ns]
 4   Request_Category     588078 non-null  object
 5   Request_SubCategory  588078 non-null  object
 6   Request_Detail       588078 non-null  object
 7   Object_Type          588078 non-null  object
 8   APN                  331558 non-null  object
 9   Street_Address       365469 non-null  object
 10  City                 588078 non-null  object
 11  State                588078 non-null  object
 12  Neighborhood         588078 non-null  object
 13  Latitude             327327 non-null  float64
 14  Longitude            327327 non-null  float64
 15  Location             327327 non-null  object
 16  Close_Time           561748 non-null  timedelta64[ns]
dtypes: datetime64[ns](2), float64(2), int64(1), object(11), timedelta64[ns](1)
memory usage: 80.8+ MB

Which columns have a lot of null values?

### Assert
The keyword `assert` is a good way for us to check if the length of the dataframe now matches the number of unique IDs.

In [39]:
assert len(berkeley_311) == berkeley_311['Case_ID'].nunique()

If the assertion is `True`, nothing happens. But if the assertion is `False`, you'll get an error. You might want to use these kinds of assertions when you have to re-run your notebooks or have to import updated datasets.

## Export a clean version of the data to a csv

We can use the `df.to_csv()` method to export a clean copy of the csv. That way, you can instantly import the clean data in a new notebook instead of rerunning the code in this notebook.

Before we run the code below, let's take a closer look:

```python
berkeley_311.to_csv('berkeley_311_clean.csv', index=False)
```

The first argument in `df.to_csv()` is the name of the file we're going to export our dataframe into. In this case, that's `berkeley_311_clean.csv`.

The second argument is `index=False`. This means that I don't want pandas to export those row ids (0, 1, 2, 3, etc.) that show up at the very lefthand side of the dataframe.

In [61]:
berkeley_311.to_csv('berkeley_311_clean.csv', index=False)

Try removing `index=False` and see what happens.